ruby "2.1.5"

source "https://rubygems.org"
source "https://rails-assets.org"

gem 'spree', github: 'spree/spree', branch: '2-4-stable'
gem 'sprangular', github: 'sprangular/sprangular'

# Provides basic authentication functionality for testing parts of your engine
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '2-4-stable'

gemspec
